# Macroeconomics project

# Task 1

### Importing essential libraries

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Loading the data and creating the DataFrame

In [7]:
# Creating a dictionary of required links 
urls = {'GDP': "https://clck.ru/32VMek",
        'PCEC': "https://clck.ru/32VMfq",
        'Investments': "https://clck.ru/32VMgX",
        'Inventories': "https://clck.ru/32VMh8",
        'GDP_Implicit_Price_Deflator_inflation': "https://clck.ru/32VMdp",
        'CPI_less_food_and_energy': "https://clck.ru/32VMdL",
        'total_CPI': "https://clck.ru/32VMb6",
        'Wilshire_5000_Full_Cap_Price_Index': "https://clck.ru/32VMZr",
        'Real_Estate_Prices': "https://clck.ru/32VLkN",
        'Short-term_rate_nominal': "https://clck.ru/32VK7V",
        'Long-term_rate_nominal': "https://clck.ru/32VJsY",
        'Yield_curve': "https://clck.ru/32VKKR",
        'Real_ef_exchange_rate': "https://clck.ru/32VM8X",
        'DM_USD_exchange_rate': "https://clck.ru/32VMS5",
        'M1':"https://clck.ru/32VP7t",
        'M3': "https://clck.ru/32VPDj",
        'Total_loans': "https://clck.ru/32VTpu"}

# Creating and populating the DataFrame with data (dates and values for each required time series)
df = pd.DataFrame()
for key in urls:
    df[f"{key} Date"] = pd.read_csv(urls[key]).iloc[:,0]
    df[key] = pd.read_csv(urls[key]).iloc[:,1]
    
# Creating and populating a dictionary by assigning to key (time series name) its DataFrame (dates and vaules)
components = {key: None for key in list(urls.keys())}
for i in range(len(urls.keys())):
    components[list(urls.keys())[i]] = pd.DataFrame(df.iloc[:,2*i]).join(pd.DataFrame(df.iloc[:,2*i+1]))
    
# Creating the final DataFrame
data_components = pd.DataFrame({'GDP Date':components['GDP'].iloc[:,0],'GDP':components['GDP'].iloc[:,1]}).rename(columns={'GDP Date':'Date'})
for i in range(len(list(components.keys()))-1):
    name = list(components.keys())[i+1]
    data_components = data_components.merge(components[list(components.keys())[i+1]],
                                           how='left', left_on='Date', right_on=f"{name} Date").drop(columns=f"{name} Date")

data_components = data_components.set_index('Date', drop=True)
data_components.loc[data_components['Real_Estate_Prices'] == '.', 'Real_Estate_Prices'] = ''
data_components.loc[data_components['Long-term_rate_nominal'] == '.', 'Long-term_rate_nominal'] = ''

In [8]:
data_components

,GDP,PCEC,GDP_Implicit_Price_Deflator_inflation,CPI_less_food_and_energy,total_CPI,Investments,Inventories,Wilshire_5000_Full_Cap_Price_Index,Real_Estate_Prices,Long-term_rate_nominal,Short-term_rate_nominal,Yield_curve,Real_ef_exchange_rate,DM_USD_exchange_rate,M1,M3
Date,,,,,,,,,,,,,,,,
1947-01-01,243.164,156.161,NaN,NaN,NaN,35.854,92.806,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1947-04-01,245.968,160.031,5.8,NaN,NaN,34.505,93.945,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1947-07-01,249.585,163.543,6.9,NaN,NaN,34.911,99.300,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1947-10-01,259.745,167.672,10.2,NaN,NaN,43.250,106.731,NaN,15710.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1948-01-01,265.742,170.372,3.2,NaN,NaN,47.202,103.061,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-01,23046.934,15813.545,6.4,2.504185,0.339103,3943.400,3176.816,43813.322344,NaN,0.05890625000000000000,3.2500000000000000,0.059687,103.364491,NaN,19168.900000,20329900000000.0000
2021-07-01,23550.420,16147.297,6.2,2.442802,0.287313,4109.122,3239.884,45986.152188,NaN,0.07281250000000000000,3.2500000000000000,0.075469,105.919162,NaN,19697.833333,20822300000000.0000
2021-10-01,24349.121,16517.976,6.8,3.238340,0.388553,4499.171,3394.375,47478.708594,NaN,0.18822580645161290323,3.2500000000000000,0.200323,108.272253,NaN,20258.000000,21327800000000.0000
2022-01-01,24740.480,16874.769,8.4,4.277553,0.532822,4671.027,3611.694,45005.218065,NaN,0.94048387096774193548,3.2943548387096774,0.980323,110.572108,NaN,20648.600000,21699300000000.0000
2022-04-01,25248.476,17261.338,9.1,5.041692,0.609753,4609.927,3777.222,40965.785000,NaN,2.1135483870967742,3.9285714285714286,2.204355,115.284173,NaN,20600.700000,21669066666666.6667

### (Optionally) Writing the DataFrame to macro.csv

In [9]:
data_components.to_csv('macro.csv')

-----